# Python review

Goals:
- recall basic Python vocabulary
- practice markdown

## Libraries and packages

**library**: a collection of code that we can use to perform specific tasks in our programs.

**NumPy**:
- core library for numerical computing in Python
- many other libraries use NumPy arrays as building blocks
- computations on NumPy are optimized for speed and memory usage


Let's import NumPy with **standard abbreviation**

In [2]:
import numpy as np

## Variables 

**variable**: a name we assign to a particular object in Python

Example:

In [3]:
# Assign a small array to a variable a
a = np.array ([[1,1,2], [3,5,8]])

In [4]:
# Run cell with the variable name to show the value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# Use 'print' function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**object** (informally speaking) is a bundle of *properties* and *action* about something specific.

Example:

Object: data frame

Propeties: number rows, names of the columns, date created

Actions: selecting a specific row, adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables.

In practice, we can often use variable and object interchangeably.


## Types
Every object in Python has a **type**. The type tells us what kind of object it is.

We can also call the type of an object, the **class** of an object and they both mean what kind of object we have.

In [6]:
print(a)

# Check the type/class of a variable/object bu using the `type` function
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [7]:
print(a[0,0])

# Check the type on an entry on the arraw by indexing
type(a[0,0])

1


numpy.int64

Notice that `type(a[0,0])` is `numpy.int64` and not juse the standard Python integer type. This is telling us that 1 is an integer stored as a 64-bit number.

In [9]:
print(a[1,1])

5


## Functions

`print` was our first example of a python **function**

Functions take in. aset of **arguments** and those arguments create an **output**.

argument = parameter.

We can ask infromation about a function by executing `?function`

In [10]:
?print


Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**

A fucntion has two types of arguments:

- **non-optional argument**: arguments *you* need to specify for the funciton to do something

- **optional argument**: arguments that are pre-filled with a default value by the function. You can ocerride them. Optional arguments appear inside the parenthesis in the form `optional_argument=default_value`

In [11]:
print('changing the default end argument', end = ' :)')

changing the default end argument :)

## Attributes & Methods

An object in python has attributes and methods.

- **attribute**: a property of an object, some piece of information about it
- **method**: a procedure associated with the object, an action where the main ingredient is the object.


### Check-in

Fish attributes:
-length, color, species

Fish methods:
- die(), bite(), swim()

**Example**
Attributes for `numpy.arrays`

We can access a variable's attributes and methods by adding a period `.` at the end of the variable's name.
`variable.method()` or `variable.attribute`

In [12]:
a.shape

(2, 3)

In [14]:
type(a.shape)

tuple

In [15]:
# Methods examples
# min() returns the minimum value along a specified axis
a.min(axis = 0)

array([1, 1, 2])

## Check-in
We can also call the `min` method without any parameters:


In [16]:
a.min()

1

Remember: methods are functions associated with an object. 

In [17]:
type(a.min)

builtin_function_or_method

## Exercise

1. Read the `print` function help. What is the type of the argument `sep`? Is this an optional or non-optional argument? Why?
The type is 'string', you can tell because it's surrounded by quotes. Optional - entering nothing defaults to ` `

2. Create two new variables, one with the integer value 77 and another one with the string 99.
`var1 = 77`
`var2 = '99'`

3. Use your variables to print `77%99%77` by changing the value of one of the optional arguments in `print`

`print(var1, var2, var1, sep='%')`

In [23]:
?print

var1 = 77
var2 = '99'

print(var1, var2, var1, sep='%')

77%99%77


Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method